### ISSUE TITLE
Eula tap skill wrong ICD

### ISSUE THREAD

**Issue by Astro-Libre** [probablyjassin/old-gaugedle#3]
Hi, I honestly have no idea as to how I can comment on the original database, so just gonna leave it here, maybe you could talk to someone with access to the DB. Eula Press Skill actually has no ICD, however in Gaugedle it says standard ICD (I've triple checked it on KQM and in DB posted on Zajef's Discord server).

**Comment by probablyjassin** [comment]
Yeah I also went to check the wiki right now, you're right. No clue how/when an error like that happened, but thank you for pointing it out! :) It'll be fixed by the time you read this! (as always, keep in mind that caching might delay it a little. when in doubt, clear browser cache)
