### ISSUE TITLE
Feature request: Option to increase max guesses from 8

### ISSUE THREAD

**Issue by qiqi-impact** [probablyjassin/old-gaugedle#4]
I'm using this game to memorize CD and some other values. The search space is so large, it would help if I could have infinite guesses. I'm currently working around it by editing main.js to comment out the 8 guesses check.

Edit: and maybe invert the guess order, but that's minor.

**Comment by probablyjassin** [comment]
That's a good idea, I'll try that out as soon as I have the time.

Should be relatively easy in principle, I'll just have to think a little about how I implement it visually for the user

**Comment by probablyjassin** [comment]
Whoops accidentally closed, I should wait with that till I'm actually done om

**Comment by probablyjassin** [comment]
closing because the repository has been moved to github.com/probablyjassin/gaugedle
